source:
  type: raw
  file: product_category_name_translation.csv

read:
  header: true
  inferSchema: true

target:
  type: bronze

write:
  mode: overwrite
  partition_strategy: coalesce
  partitions: 1