source:
  type: bronze
  table: olist_order_payments

target:
  type: silver

transformations:
  standardize_column_names: true

  trim_strings: true

  remove_duplicates:
    enabled: true
    keys:
      - order_id
      - payment_sequential

  cast_columns:
    payment_sequential: integer
    payment_installments: integer
    payment_value: decimal(12,2)

  null_handling:
    drop_if_null:
      - order_id
      - payment_type