source:
  type: bronze
  table: olist_order_items

target:
  type: silver

transformations:
  standardize_column_names: true

  trim_strings: true

  remove_duplicates:
    enabled: true
    keys:
      - order_id
      - order_item_id

  timestamp_columns:
    - shipping_limit_date

  cast_columns:
    order_item_id: integer
    price: decimal(12,2)
    freight_value: decimal(12,2)

  null_handling:
    drop_if_null:
      - order_id
      - product_id
      - seller_id