source:
  type: silver

  tables:
    orders: olist_orders
    order_items: olist_order_items
    payments: olist_order_payments
    customers: olist_customers
    products: olist_products

target:
  type: gold
  table: olist_order_summary

transformations:
  standardize_column_names: true
  trim_strings: true